### ISSUE TITLE
Example class usage

### ISSUE THREAD

**Issue by nachete1987** [Miljoen/nova-autofill#1]
Hello Miljoen,

Please, could you release an example usage class? I'm newbie with nova and dont see how to implement this interesting capabilitie.

Thanks a lot.

**Comment by piksha** [comment]
Hi @Miljoen , 

I would also love to see an example and use-case as I am struggling with implementation.

Thank you in advance.

**Comment by nachete1987** [comment]
Hi @piksha I test implementation myself but I don't obtain nothing. Maybe posting your class we could help each others

**Comment by Miljoen** [comment]
Hello @piksha and @nachete1987,

I'm sorry for the late response, I've been busy with my thesis and haven't found the time to help you guys out.

I've provided a full implementation for a fresh Laravel project, this is the project I used to make the GIF for the .readme.

Take a look at the `getAutofillData()` function in the `/app/Nova/User.php` file.

Link: https://github.com/Miljoen/test-nova/blob/master/app/Nova/User.php

**Comment by nachete1987** [comment]
Hi @Miljoen 
Thanks a lot!! I will test it right now, my use case is a bit different because I have root data in a table with categories and their configuration and a user class that obtain certain data based on categories selected with your tool. I think that with this example I could implement the user case. 
Thanks a lot and luck with your tesis!!!
