### ISSUE TITLE
Error in field.css

### ISSUE THREAD

**Issue by nachete1987** [Miljoen/nova-autofill#2]
I'm obtaining an error loading field.css. I think its produced because in FieldServiceProvider.php field.css is referenced in dist/css directory but this file is in resources/sass

file_get_contents(/home/vagrant/code/web/vendor/miljoen/nova-autofill/src/../dist/css/field.css): failed to open stream: No such file or directory {"userId":1,"exception":"[object] (ErrorException(code: 0): file_get_contents(/home/vagrant/code/web/vendor/miljoen/nova-autofill/src/../dist/css/field.css): failed to open stream: No such file or directory at /home/vagrant/code/web/vendor/laravel/nova/src/Http/Controllers/StyleController.php:28)

**Comment by nachete1987** [comment]
also, file is field.scss and field.css is in FieldServiceProvider

**Comment by Miljoen** [comment]
I've released v1.2 which should fix this issue.

Can you let me know if you can get it to work using the example implementation? :)

**Comment by nachete1987** [comment]
I will test the fix in an hour, about the test class provided, the option method need 3 parameters and 2 is passed, I fix it passing tag method that is under principal model function. I feedback you as soon as possible. Thanks at all! And sorry for my english

**Comment by Miljoen** [comment]
I've decided to rework the package, v1.4 is out now. Please follow the steps again in the .Readme, this should work! I just tested it on a fresh project!

Good luck :D
