### ISSUE TITLE
Error Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by nachete1987** [Miljoen/nova-autofill#3]
Getting Uncaught SyntaxError: Cannot use import statement outside a module in field.js

**Comment by Miljoen** [comment]
Hi @nachete1987 thanks for the feedback.

I've released v1.2 for the package, can you try to update it?

And please use the example implementation for testing, let me know if it works!

**Comment by Miljoen** [comment]
I've decided to rework the package, v1.4 is out now. Please follow the steps again in the .Readme, this should work! I just tested it on a fresh project!

Good luck :D
